SICC/SICC/Controllers/ClienteController.cs
using System;
using System.Web.Mvc;
using SICC.Models;
using SICC.Repositorio.Interface;

namespace SICC.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IClienteRepository _clienteRepository;
        private readonly IConvenioRepository _convenioRepository;
        private readonly IEmprestimoRepository _emprestimoRepository;
        private readonly IObservacaoRepository _observacaoRepository;

        public ClienteController(IClienteRepository clienteRepository, IConvenioRepository convenioRepository, IEmprestimoRepository emprestimoRepository, IObservacaoRepository observacaoRepository)
        {
            _convenioRepository = convenioRepository;
            _clienteRepository = clienteRepository;
            _emprestimoRepository = emprestimoRepository;
            _observacaoRepository = observacaoRepository;
        }
        
        // GET: Cliente
        public ActionResult Index()
        {
            return View(_clienteRepository.GetAll());
        }

        // GET: Cliente/Details/5
        public ActionResult Details(int id)
        {
            var cliente = _clienteRepository.GetById(id);
            cliente.ObjConvenio = _convenioRepository.GetById(cliente.ConvenioId);
            ViewBag.QtdEmprestimos = _emprestimoRepository.GetByCliente(id).Count;
            ViewBag.QtdObservacoes = _observacaoRepository.GetByCliente(id).Count;
            return View(_clienteRepository.GetById(id));
        }

        // GET: Cliente/Create
        public ActionResult Create()
        {
            ViewBag.Convenios = new SelectList(_convenioRepository.GetAll(), "ConvenioId","Nome", "Selecione...");
            return View();
        }

        // POST: Cliente/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cliente objCliente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    objCliente.DataCadastro = DateTime.Now;
                    _clienteRepository.Inserir(objCliente);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Create", objCliente);
            }
        }

        // GET: Cliente/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Convenios = new SelectList(_convenioRepository.GetAll(), "ConvenioId", "Nome", "Selecione...");
            return View(_clienteRepository.GetById(id));
        }

        // POST: Cliente/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Cliente objCliente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _clienteRepository.Update(objCliente);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.Convenios = new SelectList(_convenioRepository.GetAll(), "ConvenioId", "Nome", "Selecione...");
                return View();
            }
        }

        // GET: Cliente/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_clienteRepository.GetById(id));
        }

        // POST: Cliente/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Cliente objCliente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    objCliente = _clienteRepository.GetById(objCliente.ClienteId);
                    objCliente.ExclusaoLogica = true;
                    _clienteRepository.Update(objCliente);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SICC/SICC/Controllers/ConvenioController.cs
using System.Web.Mvc;
using SICC.Models;
using SICC.Repositorio.Interface;

namespace SICC.Controllers
{
    public class ConvenioController : Controller
    {
        private readonly IConvenioRepository _convenioRepository;

        public ConvenioController(IConvenioRepository convenioRepository)
        {
            _convenioRepository = convenioRepository;
        }

        // GET: Convenio
        public ActionResult Index()
        {
            return View(_convenioRepository.GetAll());
        }

       // GET: Convenio/Create
        public ActionResult Novo()
        {
            return View();
        }

        // POST: Convenio/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Novo(Convenio objConvenio)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    objConvenio.Ativo = true;
                    _convenioRepository.Inserir(objConvenio);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Novo", objConvenio);
            }
        }

        // GET: Convenio/Edit/5
        public ActionResult Editar(int id)
        {
            return View(_convenioRepository.GetById(id));
        }

        // POST: Convenio/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Convenio objConvenio)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _convenioRepository.Update(objConvenio);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Editar", objConvenio);
            }
        }

        // GET: Convenio/Delete/5
        public ActionResult Excluir(int id)
        {
            return View(_convenioRepository.GetById(id));
        }

        // POST: Convenio/Delete/5
        [HttpPost][ValidateAntiForgeryToken]
        public ActionResult Excluir(Convenio objConvenio)
        {
            try
            {
                if (ValidateRequest)
                {
                    objConvenio = _convenioRepository.GetById(objConvenio.ConvenioId);
                    objConvenio.Ativo = false;
                    _convenioRepository.Update(objConvenio);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SICC/SICC/Controllers/UsuarioController.cs
using System;
using System.Web.Mvc;
using SICC.Models;
using SICC.Models.Seguranca;
using SICC.Repositorio.Interface;

namespace SICC.Controllers
{
    //[Autenticacao]
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;

        public UsuarioController(IUsuarioRepository usuarioRepository)
        {
            _usuarioRepository = usuarioRepository;
        }

        // GET: Usuario
        public ActionResult Index()
        {
            return View(_usuarioRepository.GetByAtivos());
        }
        
        // GET: Usuario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Usuario/Create
        [HttpPost]
        public ActionResult Create(Usuario objUsuario)
        {
            try
            {
                if (ValidateRequest)
                {
                    objUsuario.DataCadastro = DateTime.Now;
                    objUsuario.Ativo = true;
                    objUsuario.SenhaInspirada = true;
                    CriarMD5 encriptar = new CriarMD5();
                    objUsuario.Senha = encriptar.RetornarMD5(objUsuario.Login + "Primeira_Senh@123"); 

                    _usuarioRepository.Inserir(objUsuario);
                    return RedirectToAction("Index");
                }
                return View(objUsuario);
            }
            catch
            {
                return View();
            }
        }

        // GET: Usuario/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_usuarioRepository.GetById(id));
        }

        // POST: Usuario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Usuario objUsuario)
        {
            try
            {
                if (ValidateRequest)
                {
                    var usuario = _usuarioRepository.GetById(objUsuario.UsuarioId);
                    usuario.Nome = objUsuario.Nome;
                    usuario.Login = objUsuario.Login;
                    usuario.Perfil = objUsuario.Perfil;
                    _usuarioRepository.Update(usuario);
                    return RedirectToAction("Index");
                }
                return View(objUsuario);
            }
            catch
            {
                return View();
            }
        }

        // GET: Usuario/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_usuarioRepository.GetById(id));
        }

        // POST: Usuario/Delete/5
        [HttpPost]
        public ActionResult Delete(Usuario objUsuario)
        {
            try
            {
                if (ValidateRequest)
                {
                    objUsuario = _usuarioRepository.GetById(objUsuario.UsuarioId);
                    objUsuario.Ativo = false;
                    _usuarioRepository.Update(objUsuario);

                    return RedirectToAction("Index");
                }
                return View(objUsuario);
            }
            catch
            {
                return View(objUsuario);
            }
        }
        [HttpPost]
        public void ResetarSenha(int usuarioId)
        {
            var usuario = _usuarioRepository.GetById(usuarioId);
            usuario.SenhaInspirada = true;
            CriarMD5 encriptar = new CriarMD5();
            usuario.Senha = encriptar.RetornarMD5(usuario.Login + "Primeira_Senh@123");
            _usuarioRepository.Update(usuario);
        }
    }
}

SICC/SICC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Agência de Negócios</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    @*<link href="/Content/sb-admin.css" rel="stylesheet">*@
    <link href="~/Content/Customizacao.css" rel="stylesheet" />
    <link href="~/Content/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header" style="font-size: 50px">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                 @*@Html.ActionLink("Agência de Negócios", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                <a href="@Url.Action("Index", "Home")" class="navbar-brand"><i class="fa fa-fw fa-line-chart"></i> Agência de Negócios</></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Index", "Cliente")"><i class="fa fa-fw fa-users"></i> Clientes</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Convenio")"><i class="fa fa-fw fa-tags"></i> Convênios</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Usuario")"><i class="fa fa-fw fa-user"></i> Usuários</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p align="center">&copy; 2017 - Hudson Fernando Mendes de França 
                <br/> hudsonhfmf@gmail.com</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/meiomask.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>