SICC/SICC/Models/Emprestimo.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SICC.Models
{
    [Table("Emprestimos")]
    public class Emprestimo
    {
        [Key]
        public int EmprestimoId { get; set; }

        [DisplayName("Valor do Emprestimo")]
        public decimal ValorEmprestimo { get; set; }

        [DisplayName("Conta")]
        public string Conta { get; set; }

        [DisplayName("Banco")]
        public string Banco { get; set; }

        [DisplayName("Quantidade de parcelas")]
        public int QuantidadeParcelas { get; set; }

        [DisplayName("Data do Emprestimo")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DataEmprestimo { get; set; }

        [DisplayName("Cliente")]
        public int ClienteId { get; set; }

        [ScaffoldColumn(false)]
        public bool ExclusaoLogica { get; set; }

        public Cliente ObjCliente { get; set; }
    }
}

SICC/SICC/Controllers/EmprestimoController.cs
using System.Web.Mvc;
using SICC.Models;
using SICC.Repositorio.Interface;

namespace SICC.Controllers
{
    public class EmprestimoController : Controller
    {
        private readonly IEmprestimoRepository _emprestimoRepository;
        private readonly IClienteRepository _clienteRepository;

        public EmprestimoController(IEmprestimoRepository emprestimoRepository, IClienteRepository clienteRepository)
        {
            _clienteRepository = clienteRepository;
            _emprestimoRepository = emprestimoRepository;
        }
        
        // GET: Emprestimo
        public ActionResult Index(int id)
        {
            var cliente = _clienteRepository.GetById(id);
            TempData["Cliente"] = cliente;
            ViewBag.NomeCliente = cliente.Nome;
            ViewBag.ClienteId = cliente.ClienteId;
            return View(_emprestimoRepository.GetByCliente(id));
        }


        // GET: Emprestimo/Create
        public ActionResult Create()
        {
            ViewBag.Cliente = (Cliente)TempData["Cliente"];
            TempData.Keep("Cliente");
            return View();
        }

        // POST: Emprestimo/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Emprestimo objEmprestimo)
        {
            try
            {
                if (ValidateRequest && ModelState.IsValid)
                {
                    var ObjCliente = (Cliente) TempData["Cliente"];
                    objEmprestimo.ClienteId = ObjCliente.ClienteId;
                    _emprestimoRepository.Inserir(objEmprestimo);
                    ViewBag.NomeCliente = ObjCliente.Nome;
                    TempData.Keep("Cliente");
                    return View("Index", _emprestimoRepository.GetByCliente(objEmprestimo.ClienteId));
                }
                ViewBag.Cliente = (Cliente)TempData["Cliente"];
                TempData.Keep("Cliente");
                return View("Create", objEmprestimo);
            }
            catch
            {
                ViewBag.Cliente = (Cliente)TempData["Cliente"];
                TempData.Keep("Cliente");
                return View("Create", objEmprestimo);
            }
        }

        // GET: Emprestimo/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Cliente = (Cliente)TempData["Cliente"];
            TempData.Keep("Cliente");
            return View(_emprestimoRepository.GetById(id));
        }

        // POST: Emprestimo/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Emprestimo objEmprestimo)
        {
            try
            {
               _emprestimoRepository.Update(objEmprestimo);
                ViewBag.NomeCliente = ((Cliente) TempData["Cliente"]).Nome;
                TempData.Keep("Cliente");
                return View("Index", _emprestimoRepository.GetByCliente(objEmprestimo.ClienteId));
            }
            catch
            {
                return View(objEmprestimo);
            }
        }

        // GET: Emprestimo/Delete/5
        public ActionResult Delete(int id)
        {
            ViewBag.Cliente = (Cliente)TempData["Cliente"];
            TempData.Keep("Cliente");
            return View(_emprestimoRepository.GetById(id));
        }

        // POST: Emprestimo/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Emprestimo objEmprestimo)
        {
            try
            {
                objEmprestimo = _emprestimoRepository.GetById(objEmprestimo.EmprestimoId);
                objEmprestimo.ExclusaoLogica = true;
                _emprestimoRepository.Update(objEmprestimo);
                ViewBag.NomeCliente = ((Cliente)TempData["Cliente"]).Nome;
                TempData.Keep("Cliente");
                return View("Index", _emprestimoRepository.GetByCliente(objEmprestimo.ClienteId));
            }
            catch
            {
                return View();
            }
        }
    }
}

SICC/SICC/Views/Emprestimo/Create.cshtml
@using SICC.Models
@model SICC.Models.Emprestimo

@{
    ViewBag.Title = "Create";
}
<br />
<div class="panel panel-Inicial">
    <div class="panel-heading"><h2><i class="glyphicon glyphicon-usd"></i> Adicionar Emprestimo</h2></div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr/>
                @Html.ValidationSummary(true, "", new {@class = "text-danger"})
               
                <div class="form-group">
                    @Html.LabelFor(model => model.ClienteId, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @{
                            var Cliente = (Cliente) ViewBag.Cliente;
                        }
                        <input type="text" disabled="disabled" value="@Cliente.Nome" class="form-control"/>
             
                        @Html.ValidationMessageFor(model => model.ClienteId, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ValorEmprestimo, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ValorEmprestimo, new {htmlAttributes = new {@class = "form-control setMaskValor"}})
                        @Html.ValidationMessageFor(model => model.ValorEmprestimo, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.QuantidadeParcelas, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.QuantidadeParcelas, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.QuantidadeParcelas, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Conta, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Conta, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Conta, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Banco, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Banco, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Banco, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DataEmprestimo, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DataEmprestimo, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.DataEmprestimo, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Salvar" class="btn btn-success"/>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="panel-footer">
        <div>
            @{
                var objCliente = (Cliente)ViewBag.Cliente;
            }
            <a href="@Url.Action("Index", "Emprestimo", new {id = @objCliente.ClienteId})" class="btn btn-default"><i class="fa fa-fw fa-arrow-left"></i> Voltar a Lista</a> 
        </div>
    </div>
</div>

SICC/SICC/Views/Emprestimo/Delete.cshtml
@using SICC.Models
@model SICC.Models.Emprestimo

@{
    ViewBag.Title = "Delete";
}

<br />
<div class="panel panel-Deletar">
    <div class="panel-heading"><h3>Realmente deseja remover este emprestimo?</h3></div>
    <div class="panel-body">
        <div>
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.ClienteId)
                </dt>
                @{
                    var Cliente = (Cliente)ViewBag.Cliente;
                }
                <dd>
                    @Html.DisplayName(@Cliente.Nome)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ValorEmprestimo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ValorEmprestimo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.QuantidadeParcelas)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.QuantidadeParcelas)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DataEmprestimo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DataEmprestimo)
                </dd>

                <br/>
                <dt>
                    @using (Html.BeginForm())
                         {
                             @Html.AntiForgeryToken()
                             @Html.HiddenFor(model => model.EmprestimoId)
                             <div class="form-actions no-color">
                                 <input type="submit" value="Delete" class="btn btn-danger"/>
                             </div>
                         }
                </dt>
            </dl>
        </div>
    </div>
    <div class="panel-footer">
        <div>
            @{
            var objCliente = (Cliente)ViewBag.Cliente;
            }
            <a href="@Url.Action("Index", "Emprestimo", new {id = @objCliente.ClienteId})" class="btn btn-default"><i class="fa fa-fw fa-arrow-left"></i> Voltar a Lista</a>
        </div>
    </div>
</div>

SICC/SICC/Views/Emprestimo/Edit.cshtml
@using SICC.Models
@model SICC.Models.Emprestimo

@{
    ViewBag.Title = "Edit";
}

<br />
<div class="panel panel-Editar">
    <div class="panel-heading"><h2>Editar dados do Emprestimo</h2></div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr/>
                @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                @Html.HiddenFor(model => model.EmprestimoId)
                @Html.HiddenFor(model => model.ClienteId)

                <div class="form-group">
                    @Html.LabelFor(model => model.ClienteId, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @{
                            var Cliente = (Cliente) ViewBag.Cliente;
                        }
                        <input type="text" disabled="disabled" value="@Cliente.Nome" class="form-control"/>

                        @Html.ValidationMessageFor(model => model.ClienteId, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ValorEmprestimo, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ValorEmprestimo, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.ValorEmprestimo, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.QuantidadeParcelas, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.QuantidadeParcelas, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.QuantidadeParcelas, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Conta, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Conta, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Conta, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Banco, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Banco, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Banco, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DataEmprestimo, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @{
                            var dataInfo = Model.DataEmprestimo;
                            string data = string.Format("{0}-{1}-{2}", dataInfo.Year, dataInfo.Month.ToString("00"), dataInfo.Day.ToString("00"));
                        }
                        <input class="form-control text-box single-line" data-val="true" data-val-date="The field Data de Emprestimo must be a date." data-val-required="O campo Data do Emprestimo é obrigatório." id="DataEmprestimo" name="DataEmprestimo" type="date" value="@data"/>
                        @Html.ValidationMessageFor(model => model.DataEmprestimo, "", new {@class = "text-danger"})

                        @Html.ValidationMessageFor(model => model.DataEmprestimo, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Salvar" class="btn btn-success"/>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="panel-footer">
        <div>
            @{
            var objCliente = (Cliente)ViewBag.Cliente;
            }
            <a href="@Url.Action("Index", "Emprestimo", new {id = @objCliente.ClienteId})" class="btn btn-default"><i class="fa fa-fw fa-arrow-left"></i> Voltar a Lista</a>
        </div>

    </div>
</div>

SICC/SICC/Views/Emprestimo/Index.cshtml
@model IEnumerable<SICC.Models.Emprestimo>

@{
    ViewBag.Title = "Index";
}
<br />
<div class="panel panel-Inicial">
    <div class="panel-heading">
        <h3>@ViewBag.NomeCliente e seus Emprestimos</h3>
    </div>
    <div class="panel-body">
        <p>
            <a href="@Url.Action("Create", "Emprestimo")" class="btn btn-primary"><i class="glyphicon glyphicon-usd"></i> Adicionar</a>
        </p>
        <table class="table table-responsive table-hover" id="tabelaEmprestimo">
            <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ValorEmprestimo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.QuantidadeParcelas)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DataEmprestimo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Banco)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Conta)
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ValorEmprestimo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.QuantidadeParcelas)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataEmprestimo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Banco)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Conta)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "Emprestimo", new {id = item.EmprestimoId})" class="btn btn-warning"><i class="glyphicon glyphicon-pencil"></i> </a> &nbsp;
                        <a href="@Url.Action("Delete", "Emprestimo", new {id = item.EmprestimoId})" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> </a> &nbsp;
                    </td>
                </tr>
            }
            </tbody>
        </table>

    </div>
    <div class="panel-footer">
        <div>
            @{
                var clienteId = ViewBag.ClienteId;
            }
            <a href="@Url.Action("Details", "Cliente", new {id = clienteId})" class="btn btn-default"><i class="fa fa-fw fa-arrow-left"></i> Voltar </a>
        </div>

    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#tabelaEmprestimo').DataTable();
        });
    </script>
}