SICC/SICC/Models/Observacao.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SICC.Models
{
    [Table("Observacoes")]
    public class Observacao
    {
        [Key]
        public int ObservacaoId { get; set; }

        [DisplayName("Margem mensal")]
        public double? MargemMensal { get; set; }

        [Required]
        [DisplayName("Anotações")]
        public string Anotacoes { get; set; }

        [DisplayName("Data da observação")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DataObservacao { get; set; }

        [DisplayName("Cliente")]
        public int ClienteId { get; set; }

        [ScaffoldColumn(false)]
        public bool ExclusaoLogica { get; set; }

        public Cliente ObjCliente { get; set; }
    }
}

SICC/SICC/Controllers/ObservacaoController.cs
using System.Web.Mvc;
using SICC.Models;
using SICC.Repositorio.Interface;

namespace SICC.Controllers
{
    public class ObservacaoController : Controller
    {
        private readonly IObservacaoRepository _observacaoRepository;
        private readonly IClienteRepository _clienteRepository;

        public ObservacaoController(IObservacaoRepository observacaoRepository, IClienteRepository clienteRepository)
        {
            _clienteRepository = clienteRepository;
            _observacaoRepository = observacaoRepository;
        }
        // GET: Observacao
        public ActionResult Index(int id)
        {
            var cliente = _clienteRepository.GetById(id);
            TempData["Cliente"] = cliente;
            ViewBag.NomeCliente = cliente.Nome;
            ViewBag.ClienteId = cliente.ClienteId;
            return View(_observacaoRepository.GetByCliente(id));
        }

        // GET: Observacao/Create
        public ActionResult Create()
        {
            ViewBag.Cliente = (Cliente)TempData["Cliente"];
            TempData.Keep("Cliente");
            return View();
        }

        // POST: Observacao/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Observacao objObservacao)
        {
            try
            {
                if (ValidateRequest && ModelState.IsValid)
                {
                    var ObjCliente = (Cliente)TempData["Cliente"];
                    objObservacao.ClienteId = ObjCliente.ClienteId;
                    _observacaoRepository.Inserir(objObservacao);
                    ViewBag.NomeCliente = ObjCliente.Nome;
                    TempData.Keep("Cliente");
                    return View("Index", _observacaoRepository.GetByCliente(objObservacao.ClienteId));
                }
                ViewBag.Cliente = (Cliente)TempData["Cliente"];
                TempData.Keep("Cliente");
                return View("Create", objObservacao);
            }
            catch
            {
                return View("Create", objObservacao);
            }
        }

        // GET: Observacao/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Cliente = (Cliente)TempData["Cliente"];
            TempData.Keep("Cliente");
            return View(_observacaoRepository.GetById(id));
        }

        // POST: Observacao/Edit/5
        [HttpPost]
        public ActionResult Edit(Observacao objObservacao)
        {
            try
            {
                _observacaoRepository.Update(objObservacao);
                ViewBag.NomeCliente = ((Cliente)TempData["Cliente"]).Nome;
                TempData.Keep("Cliente");
                return View("Index", _observacaoRepository.GetByCliente(objObservacao.ClienteId));
            }
            catch
            {
                return View(objObservacao);
            }
        }

        // GET: Observacao/Delete/5
        public ActionResult Delete(int id)
        {
            ViewBag.Cliente = (Cliente)TempData["Cliente"];
            TempData.Keep("Cliente");
            return View(_observacaoRepository.GetById(id));
        }

        // POST: Observacao/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Observacao objObservacao)
        {
            try
            {
                objObservacao = _observacaoRepository.GetById(objObservacao.ObservacaoId);
                objObservacao.ExclusaoLogica = true;
                _observacaoRepository.Update(objObservacao);
                ViewBag.NomeCliente = ((Cliente)TempData["Cliente"]).Nome;
                TempData.Keep("Cliente");
                return View("Index", _observacaoRepository.GetByCliente(objObservacao.ClienteId));
            }
            catch
            {
                return View();
            }
        }
    }
}

SICC/SICC/Views/Observacao/Create.cshtml
@using SICC.Models
@model SICC.Models.Observacao

@{
    ViewBag.Title = "Create";
}
<br />
<div class="panel panel-Inicial">
    <div class="panel-heading"><h2>Nova observação</h2></div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.ClienteId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @{

                            var Cliente = (Cliente)ViewBag.Cliente;
                        }
                        <input type="text" disabled="disabled" value="@Cliente.Nome" class="form-control" />

                        @Html.ValidationMessageFor(model => model.ClienteId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MargemMensal, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MargemMensal, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MargemMensal, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DataObservacao, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DataObservacao, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DataObservacao, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Anotacoes, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Anotacoes, new { @class = "form-control", @cols = 80, @rows = 3 })
                        @Html.ValidationMessageFor(model => model.Anotacoes, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Adicionar" class="btn btn-success" />
                    </div>
                </div>
            </div>
                            }
    </div>
    <div class="panel-footer">
        <div>
            @{
                var objCliente = (Cliente)ViewBag.Cliente;
            }
            <a href="@Url.Action("Index", "Observacao", new {id = @objCliente.ClienteId})" class="btn btn-default"><i class="fa fa-fw fa-arrow-left"></i> Voltar a Lista</a>
        </div>
    </div>

</div>

SICC/SICC/Views/Observacao/Delete.cshtml
@using SICC.Models
@model SICC.Models.Observacao

@{
    ViewBag.Title = "Delete";
}
<br />
<div class="panel panel-Deletar">
    <div class="panel-heading"><h3>Realmente deseja remover esta observação?</h3></div>
    <div class="panel-body"><div>
  <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.ClienteId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClienteId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MargemMensal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MargemMensal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anotacoes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anotacoes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataObservacao)
        </dt>

      <dd>
          @Html.DisplayFor(model => model.DataObservacao)
      </dd>
      <br/>
        <dt>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.ObservacaoId)
                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" />

                </div>
            }
        </dt>
    </dl>
  
</div></div>
    <div class="panel-footer">
        <div>
            @{
                var objCliente = (Cliente)ViewBag.Cliente;
            }
            <a href="@Url.Action("Index", "Observacao", new {id = @objCliente.ClienteId})" class="btn btn-default"><i class="fa fa-fw fa-arrow-left"></i> Voltar a Lista</a>
        </div>
    </div>
</div>

SICC/SICC/Views/Observacao/Edit.cshtml
@using SICC.Models
@model SICC.Models.Observacao

@{
    ViewBag.Title = "Edit";
}
<br />
<div class="panel panel-Editar">
    <div class="panel-heading"><h2>Editar dados da Observação</h2></div>
    <div class="panel-body">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                @Html.HiddenFor(model => model.ObservacaoId)
                @Html.HiddenFor(model => model.ClienteId)

                <div class="form-group">
                    @Html.LabelFor(model => model.ClienteId, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @{
                            var Cliente = (Cliente) ViewBag.Cliente;
                        }
                        <input type="text" disabled="disabled" value="@Cliente.Nome" class="form-control"/>
                        @Html.ValidationMessageFor(model => model.ClienteId, "", new {@class = "text-danger"})
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.MargemMensal, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MargemMensal, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.MargemMensal, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DataObservacao, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @{
                            var dataInfo = Model.DataObservacao;
                            string data = string.Format("{0}-{1}-{2}", dataInfo.Year, dataInfo.Month.ToString("00"), dataInfo.Day.ToString("00"));
                        }
                        <input class="form-control text-box single-line" data-val="true" data-val-date="The field Data de Observacao must be a date." data-val-required="O campo Data de Observacao é obrigatório." id="DataObservacao" name="DataObservacao" type="date" value="@data"/>

                        @Html.ValidationMessageFor(model => model.DataObservacao, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Anotacoes, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Anotacoes, new {@class = "form-control", @cols = 80, @rows = 3})
                        @Html.ValidationMessageFor(model => model.Anotacoes, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Salvar" class="btn btn-success  "/>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="panel-footer">
        <div>
            @{
                var objCliente = (Cliente)ViewBag.Cliente;
            }
            <a href="@Url.Action("Index", "Observacao", new {id = @objCliente.ClienteId})" class="btn btn-default"><i class="fa fa-fw fa-arrow-left"></i> Voltar a Lista</a>
        </div>
    </div>
</div>

SICC/SICC/Views/Observacao/Index.cshtml
@model IEnumerable<SICC.Models.Observacao>

@{
    ViewBag.Title = "Index";
}
<br/>
<div class="panel panel-Inicial">
    <div class="panel-heading">
        <h2>Observações sobre @ViewBag.NomeCliente</h2>
    </div>

    <div class="panel-body">
        <p>
            <a href="@Url.Action("Create", "Observacao")" class="btn btn-primary"><i class="fa fa-book"></i> Adicionar</a>
        </p>
        <table class="table table-hover" id="tabelaObservacao">
            <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.MargemMensal)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Anotacoes)
                </th>
                <th>
                @Html.DisplayNameFor(model => model.DataObservacao)
                <th></th>
            </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
            {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.MargemMensal)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Anotacoes)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DataObservacao)
                        </td>
                        <td>
                            @*@Html.ActionLink("Editar", "Edit", new { id = item.ObservacaoId }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ObservacaoId })*@
                            <a href="@Url.Action("Edit", "Observacao", new {id = item.ObservacaoId})" class="btn btn-warning"><i class="glyphicon glyphicon-pencil"></i> </a> &nbsp;
                            <a href="@Url.Action("Delete", "Observacao", new {id = item.ObservacaoId})" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> </a> &nbsp;
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="panel-footer">
        <div>
            @{
                var clienteId = ViewBag.ClienteId;
            }
            <a href="@Url.Action("Details", "Cliente", new {id = clienteId})" class="btn btn-default"><i class="fa fa-fw fa-arrow-left"></i> Voltar </a>
        </div>

    </div>
</div>


@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#tabelaObservacao').DataTable();
        });
    </script>
}